// doom_accel.h
#ifndef DOOM_ACCEL_H
#define DOOM_ACCEL_H

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>

// Constants
#define ACCEL_BASE_ADDR 0xA0000000
#define ACCEL_SIZE 0x10000
#define PHY_FB_ADDR 0x70000000    // DG_ScreenBuffer (1920x1080x4)
#define PHY_VIDEO_BUF 0x70800000  // I_VideoBuffer (320x200x1) - at 8MB offset
#define PHY_TEX_ADDR 0x70810000   // Texture Atlas (16MB)
#define PHY_CMAP_ADDR 0x71810000  // Colormap (8KB = 32 levels x 256)
#define MEM_BLOCK_SIZE 0x02000000 // 32MB total mapped region

// Register offsets for doom_accel HLS IP (unified CTRL bundle)
// These are generated by Vitis HLS - check your synthesis output if different
#define REG_CTRL 0x00           // Control: bit0=ap_start, bit1=ap_done, bit2=ap_idle, bit3=ap_ready
#define REG_GIE  0x04           // Global Interrupt Enable
#define REG_IER  0x08           // IP Interrupt Enable
#define REG_ISR  0x0C           // IP Interrupt Status

// Pointer addresses (64-bit, low then high)
#define REG_VIDEO_BUF_LO  0x10  // video_buffer address low
#define REG_VIDEO_BUF_HI  0x14  // video_buffer address high
#define REG_TEX_ATLAS_LO  0x1C  // texture_atlas address low
#define REG_TEX_ATLAS_HI  0x20  // texture_atlas address high
#define REG_COLORMAP_LO   0x28  // colormap address low
#define REG_COLORMAP_HI   0x2C  // colormap address high

// Command registers (64-bit, low then high)
#define REG_CMD1_LO       0x34  // cmd1 low (frac)
#define REG_CMD1_HI       0x38  // cmd1 high (step)
#define REG_CMD2_LO       0x40  // cmd2 low
#define REG_CMD2_HI       0x44  // cmd2 high
#define REG_CMD3_LO       0x4C  // cmd3 low (tex_offset)
#define REG_CMD3_HI       0x50  // cmd3 high (colormap_offset)

// EXTERN GLOBALS (Shared across files)
extern volatile uint32_t *accel_regs;
extern void *shared_mem_virt;
extern uint32_t *DG_ScreenBuffer;

// DEBUG FLAGS
// debug_sw_fallback: 1 = draw colored columns via CPU instead of FPGA
extern int debug_sw_fallback;

// Texture atlas pointer (virtual address of texture memory)
extern uint8_t *tex_atlas_virt;

// Rolling texture buffer offset (for uploading texture columns)
extern uint32_t tex_atlas_offset;

// Colormap pointer (virtual address of colormap memory)
extern uint8_t *colormap_virt;

// I_VideoBuffer pointer (320x200 shared buffer for unified rendering)
extern uint8_t *I_VideoBuffer_shared;

// Function Prototypes
void Init_Doom_Accel();
void HW_DrawColumn(int x, int y_start, int y_end, int step, int frac, int tex_offset, int colormap_offset);

// Upload a texture column to the atlas and return its offset
uint32_t Upload_Texture_Column(const uint8_t *source, int height);

// Upload colormap table to DDR (call once after WAD loading)
void Upload_Colormap(const uint8_t *colormaps_ptr, int size);

// Reset texture atlas offset (call at start of each frame)
void Reset_Texture_Atlas();

#endif